apiVersion: apps/v1
kind: Deployment
metadata:
  name: javademo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: javademo
  template:
    metadata:
      labels:
        app: javademo
    spec:
      containers:
      - image: https://dev-harbor.burnish.cn/ops/javademo:replace
        name: javademo
        ports:
        - containerPort: 8080
